### ISSUE TITLE
Build fails because of error at plugin

### ISSUE THREAD

**Issue by argo-qu** [danwilson/google-analytics-plugin#390]
I am using your plugin. After your last update there happened one big problem.
I am building my apps at build.phonegap.com and I got there an error message, that your plugin is the reason of build failure.

**Android logs:**
```
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

/project/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:133: error: method getVar in class UniversalAnalyticsPlugin cannot be applied to given types;
            this.getVar(callbackContext);            
                ^
  required: String,CallbackContext
  found: CallbackContext
  reason: actual and formal argument lists differ in length
/project/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:376: error: incompatible types: missing return value
            return;
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**iOS logs:**
```
The following build commands failed: 	CompileC /Users/phonegap/Library/Developer/Xcode/DerivedData/Precalculus-bjpdeaunxhvxiqgheclbhnpzascg/Build/Intermediates/ArchiveIntermediates/Precalculus/IntermediateBuildFilesPath/Precalculus.build/Release-iphoneos/Precalculus.build/Objects-normal/armv7/UniversalAnalyticsPlugin.o Precalculus/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure) Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,Precalculus.xcworkspace,-scheme,Precalculus,-configuration,Release,-destination,generic/platform=iOS,-archivePath,Precalculus.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch
```

**Comment by brobx** [comment]
I also have the same issue when make build with cross-walk olugin

**Comment by fcostazini** [comment]
Same here!
Android works great. when trying to build on IOS i get the same error.
i've already tried rm/add platform and plugins
cordova CLI: 5.0.0 
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by kleeb** [comment]
the same for me

```
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:133: error: method getVar in class UniversalAnalyticsPlugin cannot be applied to given types;
            this.getVar(callbackContext);            
                ^
  required: String,CallbackContext
  found: CallbackContext
  reason: actual and formal argument lists differ in length
/project/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:376: error: incompatible types: missing return value
            return;
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.248 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

/project/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:133: error: method getVar in class UniversalAnalyticsPlugin cannot be applied to given types;
            this.getVar(callbackContext);            
                ^
  required: String,CallbackContext
  found: CallbackContext
  reason: actual and formal argument lists differ in length
/project/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:376: error: incompatible types: missing return value
            return;
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by victorsosa** [comment]
I am fixing the issue, thank

**Comment by victorsosa** [comment]
fixed please try again with v1.7.7

**Comment by kleeb** [comment]
still 1.7.6 on npm

**Comment by victorsosa** [comment]
give it some minutes; it should be up soon

**Comment by Armanio** [comment]
Not fixed.

Please accept pull request.
https://github.com/danwilson/google-analytics-plugin/pull/392

**Comment by brobx** [comment]
Updated with 1.7.7 and still the same error

**Comment by victorsosa** [comment]
@Armanio thanks, PR accepted, please get the last version 1.7.8
